export const mappedData = (array: any[]) => {
  const help = (level: number, paths: string[]): any => {
    return array
      .map((item) => {
        let tmp = [...paths, item.standardCategoryId];
        if (
          item.standardCategoryDepth === level &&
          tmp.join(" , ") === item.standardCategoryPathId
        ) {
          const children = help(level + 1, tmp);
          return { ...item, children: children };
        }
      })
      .filter(Boolean);
  };
  return help(1, []);
};


export const fakeData = [
  {
    standardCategoryId: "SC1DE001",
    upperStandardCategoryId: "",
    standardCategoryName: "식품123213123",
    standardCategoryDepth: 1,
    productCount: 82,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "식품123213123",
    standardCategoryPathId: "SC1DE001",
  },
  {
    standardCategoryId: "SC3DE055",
    upperStandardCategoryId: "SC2DE001",
    standardCategoryName: "123",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 15,
    standardCategoryPathName: "식품123213123 > 과일1234523 > 123",
    standardCategoryPathId: "SC1DE001 , SC2DE001 , SC3DE055",
  },
  {
    standardCategoryId: "SC3DE079",
    upperStandardCategoryId: "SC2DE001",
    standardCategoryName: "123",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 18,
    standardCategoryPathName: "식품123213123 > 과일1234523 > 123",
    standardCategoryPathId: "SC1DE001 , SC2DE001 , SC3DE079",
  },
  {
    standardCategoryId: "SC3DE001",
    upperStandardCategoryId: "SC2DE001",
    standardCategoryName: "사과aa1212",
    standardCategoryDepth: 3,
    productCount: 18,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "식품123213123 > 과일1234523 > 사과aa1212",
    standardCategoryPathId: "SC1DE001 , SC2DE001 , SC3DE001",
  },
  {
    standardCategoryId: "SC2DE061",
    upperStandardCategoryId: "SC2DE001",
    standardCategoryName: "test",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "식품123213123 > 과일1234523 > test",
    standardCategoryPathId: "SC1DE001 , SC2DE001 , SC2DE061",
  },
  {
    standardCategoryId: "SC3DE003",
    upperStandardCategoryId: "SC2DE001",
    standardCategoryName: "포도",
    standardCategoryDepth: 3,
    productCount: 63,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "식품123213123 > 과일1234523 > 포도",
    standardCategoryPathId: "SC1DE001 , SC2DE001 , SC3DE003",
  },
  {
    standardCategoryId: "SC3DE030",
    upperStandardCategoryId: "SC2DE001",
    standardCategoryName: "수박",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 5,
    standardCategoryPathName: "식품123213123 > 과일1234523 > 수박",
    standardCategoryPathId: "SC1DE001 , SC2DE001 , SC3DE030",
  },
  {
    standardCategoryId: "SC3DE035",
    upperStandardCategoryId: "SC2DE001",
    standardCategoryName: "수박",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 6,
    standardCategoryPathName: "식품123213123 > 과일1234523 > 수박",
    standardCategoryPathId: "SC1DE001 , SC2DE001 , SC3DE035",
  },
  {
    standardCategoryId: "SC3DE004",
    upperStandardCategoryId: "SC2DE002",
    standardCategoryName: "고구마",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "식품123213123 > 채소 > 고구마",
    standardCategoryPathId: "SC1DE001 , SC2DE002 , SC3DE004",
  },
  {
    standardCategoryId: "SC3DE060",
    upperStandardCategoryId: "SC2DE002",
    standardCategoryName: "213123",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "식품123213123 > 채소 > 213123",
    standardCategoryPathId: "SC1DE001 , SC2DE002 , SC3DE060",
  },
  {
    standardCategoryId: "SC3DE067",
    upperStandardCategoryId: "SC2DE002",
    standardCategoryName: "123",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 5,
    standardCategoryPathName: "식품123213123 > 채소 > 123",
    standardCategoryPathId: "SC1DE001 , SC2DE002 , SC3DE067",
  },
  {
    standardCategoryId: "SC3DE007",
    upperStandardCategoryId: "SC2DE003",
    standardCategoryName: "오징어",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "식품123213123 > 수산/건어물 > 오징어",
    standardCategoryPathId: "SC1DE001 , SC2DE003 , SC3DE007",
  },
  {
    standardCategoryId: "SC3DE008",
    upperStandardCategoryId: "SC2DE003",
    standardCategoryName: "우럭",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "식품123213123 > 수산/건어물 > 우럭",
    standardCategoryPathId: "SC1DE001 , SC2DE003 , SC3DE008",
  },
  {
    standardCategoryId: "SC3DE009",
    upperStandardCategoryId: "SC2DE003",
    standardCategoryName: "새우",
    standardCategoryDepth: 3,
    productCount: 1,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "식품123213123 > 수산/건어물 > 새우",
    standardCategoryPathId: "SC1DE001 , SC2DE003 , SC3DE009",
  },
  {
    standardCategoryId: "SC3DE117",
    upperStandardCategoryId: "SC2DE003",
    standardCategoryName: "Test12",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "식품123213123 > 수산/건어물 > Test12",
    standardCategoryPathId: "SC1DE001 , SC2DE003 , SC3DE117",
  },
  {
    standardCategoryId: "SC3DE118",
    upperStandardCategoryId: "SC2DE003",
    standardCategoryName: "Test13",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 5,
    standardCategoryPathName: "식품123213123 > 수산/건어물 > Test13",
    standardCategoryPathId: "SC1DE001 , SC2DE003 , SC3DE118",
  },
  {
    standardCategoryId: "SC3DE130",
    upperStandardCategoryId: "SC2DE003",
    standardCategoryName: "test11",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 6,
    standardCategoryPathName: "식품123213123 > 수산/건어물 > test11",
    standardCategoryPathId: "SC1DE001 , SC2DE003 , SC3DE130",
  },
  {
    standardCategoryId: "SC3DE127",
    upperStandardCategoryId: "SC2DE060",
    standardCategoryName: "detail depth3 ko xoa",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName:
      "식품123213123 > Xin dung xoa > detail depth3 ko xoa",
    standardCategoryPathId: "SC1DE001 , SC2DE060 , SC3DE127",
  },
  {
    standardCategoryId: "SC2DE002",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "채소",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "식품123213123 > 채소",
    standardCategoryPathId: "SC1DE001 , SC2DE002",
  },
  {
    standardCategoryId: "SC2DE003",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "수산/건어물",
    standardCategoryDepth: 2,
    productCount: 1,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "식품123213123 > 수산/건어물",
    standardCategoryPathId: "SC1DE001 , SC2DE003",
  },
  {
    standardCategoryId: "SC2DE052",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "tesst789",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 10,
    standardCategoryPathName: "식품123213123 > tesst789",
    standardCategoryPathId: "SC1DE001 , SC2DE052",
  },
  {
    standardCategoryId: "SC2DE058",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "test12",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 11,
    standardCategoryPathName: "식품123213123 > test12",
    standardCategoryPathId: "SC1DE001 , SC2DE058",
  },
  {
    standardCategoryId: "SC2DE060",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "Xin dung xoa",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 12,
    standardCategoryPathName: "식품123213123 > Xin dung xoa",
    standardCategoryPathId: "SC1DE001 , SC2DE060",
  },
  {
    standardCategoryId: "SC2DE001",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "과일1234523",
    standardCategoryDepth: 2,
    productCount: 81,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "식품123213123 > 과일1234523",
    standardCategoryPathId: "SC1DE001 , SC2DE001",
  },
  {
    standardCategoryId: "SC2DE044",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "123",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "식품123213123 > 123",
    standardCategoryPathId: "SC1DE001 , SC2DE044",
  },
  {
    standardCategoryId: "SC2DE045",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "123",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 5,
    standardCategoryPathName: "식품123213123 > 123",
    standardCategoryPathId: "SC1DE001 , SC2DE045",
  },
  {
    standardCategoryId: "SC2DE046",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "123123",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 6,
    standardCategoryPathName: "식품123213123 > 123123",
    standardCategoryPathId: "SC1DE001 , SC2DE046",
  },
  {
    standardCategoryId: "SC2DE047",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "123123",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 8,
    standardCategoryPathName: "식품123213123 > 123123",
    standardCategoryPathId: "SC1DE001 , SC2DE047",
  },
  {
    standardCategoryId: "SC2DE048",
    upperStandardCategoryId: "SC1DE001",
    standardCategoryName: "123",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 9,
    standardCategoryPathName: "식품123213123 > 123",
    standardCategoryPathId: "SC1DE001 , SC2DE048",
  },
  {
    standardCategoryId: "SC1DE002",
    upperStandardCategoryId: null,
    standardCategoryName: "여성패션",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "여성패션",
    standardCategoryPathId: "SC1DE002",
  },
  {
    standardCategoryId: "SC3DE012",
    upperStandardCategoryId: "SC2DE004",
    standardCategoryName: "팬츠",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "여성패션 > 의류 > 팬츠",
    standardCategoryPathId: "SC1DE002 , SC2DE004 , SC3DE012",
  },
  {
    standardCategoryId: "SC3DE010",
    upperStandardCategoryId: "SC2DE004",
    standardCategoryName: "가디건",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "여성패션 > 의류 > 가디건",
    standardCategoryPathId: "SC1DE002 , SC2DE004 , SC3DE010",
  },
  {
    standardCategoryId: "SC3DE113",
    upperStandardCategoryId: "SC2DE004",
    standardCategoryName: "hhh",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "여성패션 > 의류 > hhh",
    standardCategoryPathId: "SC1DE002 , SC2DE004 , SC3DE113",
  },
  {
    standardCategoryId: "SC3DE114",
    upperStandardCategoryId: "SC2DE004",
    standardCategoryName: "teste3",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "여성패션 > 의류 > teste3",
    standardCategoryPathId: "SC1DE002 , SC2DE004 , SC3DE114",
  },
  {
    standardCategoryId: "SC3DE115",
    upperStandardCategoryId: "SC2DE004",
    standardCategoryName: "test12",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 5,
    standardCategoryPathName: "여성패션 > 의류 > test12",
    standardCategoryPathId: "SC1DE002 , SC2DE004 , SC3DE115",
  },
  {
    standardCategoryId: "SC2DE004",
    upperStandardCategoryId: "SC1DE002",
    standardCategoryName: "의류",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "여성패션 > 의류",
    standardCategoryPathId: "SC1DE002 , SC2DE004",
  },
  {
    standardCategoryId: "SC1DE003",
    upperStandardCategoryId: "",
    standardCategoryName: "123",
    standardCategoryDepth: 1,
    productCount: 3,
    standardCategoryDisplayOrder: 0,
    standardCategoryPathName: "123",
    standardCategoryPathId: "SC1DE003",
  },
  {
    standardCategoryId: "SC3DE019",
    upperStandardCategoryId: "SC2DE007",
    standardCategoryName: "바지",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "123 > 의류 > 바지",
    standardCategoryPathId: "SC1DE003 , SC2DE007 , SC3DE019",
  },
  {
    standardCategoryId: "SC3DE020",
    upperStandardCategoryId: "SC2DE007",
    standardCategoryName: "정장",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "123 > 의류 > 정장",
    standardCategoryPathId: "SC1DE003 , SC2DE007 , SC3DE020",
  },
  {
    standardCategoryId: "SC3DE021",
    upperStandardCategoryId: "SC2DE007",
    standardCategoryName: "셔츠",
    standardCategoryDepth: 3,
    productCount: 1,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "123 > 의류 > 셔츠",
    standardCategoryPathId: "SC1DE003 , SC2DE007 , SC3DE021",
  },
  {
    standardCategoryId: "SC3DE121",
    upperStandardCategoryId: "SC2DE007",
    standardCategoryName: "@@@",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "123 > 의류 > @@@",
    standardCategoryPathId: "SC1DE003 , SC2DE007 , SC3DE121",
  },
  {
    standardCategoryId: "SC3DE022",
    upperStandardCategoryId: "SC2DE008",
    standardCategoryName: "가방",
    standardCategoryDepth: 3,
    productCount: 1,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "123 > 가방/지갑 > 가방",
    standardCategoryPathId: "SC1DE003 , SC2DE008 , SC3DE022",
  },
  {
    standardCategoryId: "SC3DE023",
    upperStandardCategoryId: "SC2DE008",
    standardCategoryName: "지갑",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "123 > 가방/지갑 > 지갑",
    standardCategoryPathId: "SC1DE003 , SC2DE008 , SC3DE023",
  },
  {
    standardCategoryId: "SC3DE024",
    upperStandardCategoryId: "SC2DE008",
    standardCategoryName: "벨트",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "123 > 가방/지갑 > 벨트",
    standardCategoryPathId: "SC1DE003 , SC2DE008 , SC3DE024",
  },
  {
    standardCategoryId: "SC3DE085",
    upperStandardCategoryId: "SC2DE008",
    standardCategoryName: "tse",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "123 > 가방/지갑 > tse",
    standardCategoryPathId: "SC1DE003 , SC2DE008 , SC3DE085",
  },
  {
    standardCategoryId: "SC3DE027",
    upperStandardCategoryId: "SC2DE009",
    standardCategoryName: "정장화",
    standardCategoryDepth: 3,
    productCount: 1,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "123 > 신발 > 정장화",
    standardCategoryPathId: "SC1DE003 , SC2DE009 , SC3DE027",
  },
  {
    standardCategoryId: "SC2DE008",
    upperStandardCategoryId: "SC1DE003",
    standardCategoryName: "가방/지갑",
    standardCategoryDepth: 2,
    productCount: 1,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "123 > 가방/지갑",
    standardCategoryPathId: "SC1DE003 , SC2DE008",
  },
  {
    standardCategoryId: "SC2DE007",
    upperStandardCategoryId: "SC1DE003",
    standardCategoryName: "의류",
    standardCategoryDepth: 2,
    productCount: 1,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "123 > 의류",
    standardCategoryPathId: "SC1DE003 , SC2DE007",
  },
  {
    standardCategoryId: "SC2DE009",
    upperStandardCategoryId: "SC1DE003",
    standardCategoryName: "신발",
    standardCategoryDepth: 2,
    productCount: 1,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "123 > 신발",
    standardCategoryPathId: "SC1DE003 , SC2DE009",
  },
  {
    standardCategoryId: "SC2DE011",
    upperStandardCategoryId: "SC1DE003",
    standardCategoryName: "중분류2",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "123 > 중분류2",
    standardCategoryPathId: "SC1DE003 , SC2DE011",
  },
  {
    standardCategoryId: "SC1DE004",
    upperStandardCategoryId: "",
    standardCategoryName: "depth1",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "depth1",
    standardCategoryPathId: "SC1DE004",
  },
  {
    standardCategoryId: "SC2DE017",
    upperStandardCategoryId: "SC1DE004",
    standardCategoryName: "depth2",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "depth1 > depth2",
    standardCategoryPathId: "SC1DE004 , SC2DE017",
  },
  {
    standardCategoryId: "SC1DE008",
    upperStandardCategoryId: "",
    standardCategoryName: "test 2",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "test 2",
    standardCategoryPathId: "SC1DE008",
  },
  {
    standardCategoryId: "SC3DE063",
    upperStandardCategoryId: "SC2DE040",
    standardCategoryName: "tetsss",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "test 2 > teste > tetsss",
    standardCategoryPathId: "SC1DE008 , SC2DE040 , SC3DE063",
  },
  {
    standardCategoryId: "SC2DE040",
    upperStandardCategoryId: "SC1DE008",
    standardCategoryName: "teste",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "test 2 > teste",
    standardCategoryPathId: "SC1DE008 , SC2DE040",
  },
  {
    standardCategoryId: "SC1DE015",
    upperStandardCategoryId: "",
    standardCategoryName: "213123123",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 0,
    standardCategoryPathName: "213123123",
    standardCategoryPathId: "SC1DE015",
  },
  {
    standardCategoryId: "SC3DE051",
    upperStandardCategoryId: "SC2DE029",
    standardCategoryName: "mytest3",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "213123123 > mytest > mytest3",
    standardCategoryPathId: "SC1DE015 , SC2DE029 , SC3DE051",
  },
  {
    standardCategoryId: "SC3DE083",
    upperStandardCategoryId: "SC2DE029",
    standardCategoryName: "mytest3.1",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "213123123 > mytest > mytest3.1",
    standardCategoryPathId: "SC1DE015 , SC2DE029 , SC3DE083",
  },
  {
    standardCategoryId: "SC3DE084",
    upperStandardCategoryId: "SC2DE029",
    standardCategoryName: "mytest3.2",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "213123123 > mytest > mytest3.2",
    standardCategoryPathId: "SC1DE015 , SC2DE029 , SC3DE084",
  },
  {
    standardCategoryId: "SC2DE029",
    upperStandardCategoryId: "SC1DE015",
    standardCategoryName: "mytest",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "213123123 > mytest",
    standardCategoryPathId: "SC1DE015 , SC2DE029",
  },
  {
    standardCategoryId: "SC1DE037",
    upperStandardCategoryId: "",
    standardCategoryName: "aaa",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "aaa",
    standardCategoryPathId: "SC1DE037",
  },
  {
    standardCategoryId: "SC3DE061",
    upperStandardCategoryId: "SC2DE038",
    standardCategoryName: "커피/음료",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "aaa > 모바일쿠폰 > 커피/음료",
    standardCategoryPathId: "SC1DE037 , SC2DE038 , SC3DE061",
  },
  {
    standardCategoryId: "SC2DE038",
    upperStandardCategoryId: "SC1DE037",
    standardCategoryName: "모바일쿠폰",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "aaa > 모바일쿠폰",
    standardCategoryPathId: "SC1DE037 , SC2DE038",
  },
  {
    standardCategoryId: "SC1DE039",
    upperStandardCategoryId: "",
    standardCategoryName: "newTest123",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "newTest123",
    standardCategoryPathId: "SC1DE039",
  },
  {
    standardCategoryId: "SC3DE065",
    upperStandardCategoryId: "SC2DE039",
    standardCategoryName: "depth33",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "newTest123 > depth2 > depth33",
    standardCategoryPathId: "SC1DE039 , SC2DE039 , SC3DE065",
  },
  {
    standardCategoryId: "SC3DE062",
    upperStandardCategoryId: "SC2DE039",
    standardCategoryName: "depth3",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "newTest123 > depth2 > depth3",
    standardCategoryPathId: "SC1DE039 , SC2DE039 , SC3DE062",
  },
  {
    standardCategoryId: "SC3DE066",
    upperStandardCategoryId: "SC2DE039",
    standardCategoryName: "depth333",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "newTest123 > depth2 > depth333",
    standardCategoryPathId: "SC1DE039 , SC2DE039 , SC3DE066",
  },
  {
    standardCategoryId: "SC2DE039",
    upperStandardCategoryId: "SC1DE039",
    standardCategoryName: "depth2",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "newTest123 > depth2",
    standardCategoryPathId: "SC1DE039 , SC2DE039",
  },
  {
    standardCategoryId: "SC1DE040",
    upperStandardCategoryId: "",
    standardCategoryName: "11/01 0928",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 5,
    standardCategoryPathName: "11/01 0928",
    standardCategoryPathId: "SC1DE040",
  },
  {
    standardCategoryId: "SC3DE064",
    upperStandardCategoryId: "SC2DE041",
    standardCategoryName: "test5",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 10,
    standardCategoryPathName: "11/01 0928 > 11/01 0928 2 > test5",
    standardCategoryPathId: "SC1DE040 , SC2DE041 , SC3DE064",
  },
  {
    standardCategoryId: "SC3DE119",
    upperStandardCategoryId: "SC2DE041",
    standardCategoryName: "Test6",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 11,
    standardCategoryPathName: "11/01 0928 > 11/01 0928 2 > Test6",
    standardCategoryPathId: "SC1DE040 , SC2DE041 , SC3DE119",
  },
  {
    standardCategoryId: "SC3DE120",
    upperStandardCategoryId: "SC2DE041",
    standardCategoryName: "Test7",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 12,
    standardCategoryPathName: "11/01 0928 > 11/01 0928 2 > Test7",
    standardCategoryPathId: "SC1DE040 , SC2DE041 , SC3DE120",
  },
  {
    standardCategoryId: "SC3DE070",
    upperStandardCategoryId: "SC2DE041",
    standardCategoryName: "test1",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "11/01 0928 > 11/01 0928 2 > test1",
    standardCategoryPathId: "SC1DE040 , SC2DE041 , SC3DE070",
  },
  {
    standardCategoryId: "SC2DE041",
    upperStandardCategoryId: "SC1DE040",
    standardCategoryName: "11/01 0928 2",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "11/01 0928 > 11/01 0928 2",
    standardCategoryPathId: "SC1DE040 , SC2DE041",
  },
  {
    standardCategoryId: "SC1DE043",
    upperStandardCategoryId: "",
    standardCategoryName: "12333",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "12333",
    standardCategoryPathId: "SC1DE043",
  },
  {
    standardCategoryId: "SC3DE080",
    upperStandardCategoryId: "SC2DE050",
    standardCategoryName: "asdf",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "12333 > asd > asdf",
    standardCategoryPathId: "SC1DE043 , SC2DE050 , SC3DE080",
  },
  {
    standardCategoryId: "SC2DE050",
    upperStandardCategoryId: "SC1DE043",
    standardCategoryName: "asd",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "12333 > asd",
    standardCategoryPathId: "SC1DE043 , SC2DE050",
  },
  {
    standardCategoryId: "SC1DE048",
    upperStandardCategoryId: "",
    standardCategoryName: "vi tri 2 1",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "vi tri 2 1",
    standardCategoryPathId: "SC1DE048",
  },
  {
    standardCategoryId: "SC1DE049",
    upperStandardCategoryId: "",
    standardCategoryName: "vi tri  1",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "vi tri  1",
    standardCategoryPathId: "SC1DE049",
  },
  {
    standardCategoryId: "SC1DE050",
    upperStandardCategoryId: "",
    standardCategoryName: "hhh",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 13,
    standardCategoryPathName: "hhh",
    standardCategoryPathId: "SC1DE050",
  },
  {
    standardCategoryId: "SC3DE086",
    upperStandardCategoryId: "SC2DE054",
    standardCategoryName: "1234",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "hhh > hhh1 > 1234",
    standardCategoryPathId: "SC1DE050 , SC2DE054 , SC3DE086",
  },
  {
    standardCategoryId: "SC2DE054",
    upperStandardCategoryId: "SC1DE050",
    standardCategoryName: "hhh1",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "hhh > hhh1",
    standardCategoryPathId: "SC1DE050 , SC2DE054",
  },
  {
    standardCategoryId: "SC1DE051",
    upperStandardCategoryId: "",
    standardCategoryName: "test11111112",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 14,
    standardCategoryPathName: "test11111112",
    standardCategoryPathId: "SC1DE051",
  },
  {
    standardCategoryId: "SC3DE087",
    upperStandardCategoryId: "SC2DE055",
    standardCategoryName: "111111111",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "test11111112 > tét 11111111123 > 111111111",
    standardCategoryPathId: "SC1DE051 , SC2DE055 , SC3DE087",
  },
  {
    standardCategoryId: "SC3DE090",
    upperStandardCategoryId: "SC2DE055",
    standardCategoryName: "222222222",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "test11111112 > tét 11111111123 > 222222222",
    standardCategoryPathId: "SC1DE051 , SC2DE055 , SC3DE090",
  },
  {
    standardCategoryId: "SC3DE109",
    upperStandardCategoryId: "SC2DE055",
    standardCategoryName: "test",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 3,
    standardCategoryPathName: "test11111112 > tét 11111111123 > test",
    standardCategoryPathId: "SC1DE051 , SC2DE055 , SC3DE109",
  },
  {
    standardCategoryId: "SC3DE110",
    upperStandardCategoryId: "SC2DE055",
    standardCategoryName: "test",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "test11111112 > tét 11111111123 > test",
    standardCategoryPathId: "SC1DE051 , SC2DE055 , SC3DE110",
  },
  {
    standardCategoryId: "SC3DE122",
    upperStandardCategoryId: "SC2DE055",
    standardCategoryName: "depth3",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 6,
    standardCategoryPathName: "test11111112 > tét 11111111123 > depth3",
    standardCategoryPathId: "SC1DE051 , SC2DE055 , SC3DE122",
  },
  {
    standardCategoryId: "SC3DE123",
    upperStandardCategoryId: "SC2DE055",
    standardCategoryName: "depth32",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 7,
    standardCategoryPathName: "test11111112 > tét 11111111123 > depth32",
    standardCategoryPathId: "SC1DE051 , SC2DE055 , SC3DE123",
  },
  {
    standardCategoryId: "SC2DE055",
    upperStandardCategoryId: "SC1DE051",
    standardCategoryName: "tét 11111111123",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "test11111112 > tét 11111111123",
    standardCategoryPathId: "SC1DE051 , SC2DE055",
  },
  {
    standardCategoryId: "SC1DE052",
    upperStandardCategoryId: "",
    standardCategoryName: "test11",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "test11",
    standardCategoryPathId: "SC1DE052",
  },
  {
    standardCategoryId: "SC2DE056",
    upperStandardCategoryId: "SC1DE052",
    standardCategoryName: "test2",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "test11 > test2",
    standardCategoryPathId: "SC1DE052 , SC2DE056",
  },
  {
    standardCategoryId: "SC1DE054",
    upperStandardCategoryId: "",
    standardCategoryName: "`1",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "`1",
    standardCategoryPathId: "SC1DE054",
  },
  {
    standardCategoryId: "SC3DE108",
    upperStandardCategoryId: "SC2DE057",
    standardCategoryName: "123,1",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "`1 > 123 > 123,1",
    standardCategoryPathId: "SC1DE054 , SC2DE057 , SC3DE108",
  },
  {
    standardCategoryId: "SC2DE057",
    upperStandardCategoryId: "SC1DE054",
    standardCategoryName: "123",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "`1 > 123",
    standardCategoryPathId: "SC1DE054 , SC2DE057",
  },
  {
    standardCategoryId: "SC1DE056",
    upperStandardCategoryId: "",
    standardCategoryName: "@@@",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "@@@",
    standardCategoryPathId: "SC1DE056",
  },
  {
    standardCategoryId: "SC1DE057",
    upperStandardCategoryId: "",
    standardCategoryName: "4566556",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "4566556",
    standardCategoryPathId: "SC1DE057",
  },
  {
    standardCategoryId: "SC1DE058",
    upperStandardCategoryId: "",
    standardCategoryName: "mytest1",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 17,
    standardCategoryPathName: "mytest1",
    standardCategoryPathId: "SC1DE058",
  },
  {
    standardCategoryId: "SC3DE124",
    upperStandardCategoryId: "SC2DE059",
    standardCategoryName: "3rd-my",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "mytest1 > 2nd-my > 3rd-my",
    standardCategoryPathId: "SC1DE058 , SC2DE059 , SC3DE124",
  },
  {
    standardCategoryId: "SC3DE125",
    upperStandardCategoryId: "SC2DE059",
    standardCategoryName: "3rd-my1",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 2,
    standardCategoryPathName: "mytest1 > 2nd-my > 3rd-my1",
    standardCategoryPathId: "SC1DE058 , SC2DE059 , SC3DE125",
  },
  {
    standardCategoryId: "SC3DE128",
    upperStandardCategoryId: "SC2DE059",
    standardCategoryName: "3rd-my3",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 4,
    standardCategoryPathName: "mytest1 > 2nd-my > 3rd-my3",
    standardCategoryPathId: "SC1DE058 , SC2DE059 , SC3DE128",
  },
  {
    standardCategoryId: "SC2DE059",
    upperStandardCategoryId: "SC1DE058",
    standardCategoryName: "2nd-my",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "mytest1 > 2nd-my",
    standardCategoryPathId: "SC1DE058 , SC2DE059",
  },
  {
    standardCategoryId: "SC1DE059",
    upperStandardCategoryId: "",
    standardCategoryName: "test l0111",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 21,
    standardCategoryPathName: "test l0111",
    standardCategoryPathId: "SC1DE059",
  },
  {
    standardCategoryId: "SC3DE131",
    upperStandardCategoryId: "SC2DE063",
    standardCategoryName: "depth333",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "test l0111 > depth2222 > depth333",
    standardCategoryPathId: "SC1DE059 , SC2DE063 , SC3DE131",
  },
  {
    standardCategoryId: "SC2DE063",
    upperStandardCategoryId: "SC1DE059",
    standardCategoryName: "depth2222",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "test l0111 > depth2222",
    standardCategoryPathId: "SC1DE059 , SC2DE063",
  },
  {
    standardCategoryId: "SC1DE060",
    upperStandardCategoryId: "",
    standardCategoryName: "depth1",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "depth1",
    standardCategoryPathId: "SC1DE060",
  },
  {
    standardCategoryId: "SC1DE061",
    upperStandardCategoryId: "",
    standardCategoryName: "depth",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "depth",
    standardCategoryPathId: "SC1DE061",
  },
  {
    standardCategoryId: "SC1DE063",
    upperStandardCategoryId: "",
    standardCategoryName: "123",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "123",
    standardCategoryPathId: "SC1DE063",
  },
  {
    standardCategoryId: "SC1DE065",
    upperStandardCategoryId: "",
    standardCategoryName: "213213",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 25,
    standardCategoryPathName: "213213",
    standardCategoryPathId: "SC1DE065",
  },
  {
    standardCategoryId: "SC2DE065",
    upperStandardCategoryId: "SC1DE065",
    standardCategoryName: "213213",
    standardCategoryDepth: 2,
    productCount: null,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "213213 > 213213",
    standardCategoryPathId: "SC1DE065 , SC2DE065",
  },
  {
    standardCategoryId: "SC1DE066",
    upperStandardCategoryId: "",
    standardCategoryName: "123",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 26,
    standardCategoryPathName: "123",
    standardCategoryPathId: "SC1DE066",
  },
  {
    standardCategoryId: "SC1DE067",
    upperStandardCategoryId: "",
    standardCategoryName: "12321",
    standardCategoryDepth: 1,
    productCount: 0,
    standardCategoryDisplayOrder: 27,
    standardCategoryPathName: "12321",
    standardCategoryPathId: "SC1DE067",
  },
  {
    standardCategoryId: "SC3DE132",
    upperStandardCategoryId: "SC2DE066",
    standardCategoryName: "34",
    standardCategoryDepth: 3,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "12321 > sds > 34",
    standardCategoryPathId: "SC1DE067 , SC2DE066 , SC3DE132",
  },
  {
    standardCategoryId: "SC2DE066",
    upperStandardCategoryId: "SC1DE067",
    standardCategoryName: "sds",
    standardCategoryDepth: 2,
    productCount: 0,
    standardCategoryDisplayOrder: 1,
    standardCategoryPathName: "12321 > sds",
    standardCategoryPathId: "SC1DE067 , SC2DE066",
  },
  {
    standardCategoryId: "SC1DE068",
    upperStandardCategoryId: "",
    standardCategoryName: "hiii",
    standardCategoryDepth: 1,
    productCount: null,
    standardCategoryDisplayOrder: 27,
    standardCategoryPathName: "hiii",
    standardCategoryPathId: "SC1DE068",
  },
];
